services:
  serverfolderwatch:
    image: serverfolderwatch:0.3.0
    container_name: serverfolderwatch

    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - App__RootPublicPath=/public
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/public
    
    # make the server console output colorful :)
    tty: true 
